
from os import sys
from Jawa import *
from ROOT import TFile, TTree, TH1, TCut, kRed, kYellow, kBlue, kOrange, kGreen, TF1, kMagenta, TMath, TH1F, TCanvas

from Wjconfig_new import *

zmup_jeteff = EfficiencyClass("zmup_seleff")
zmup_jeteff.SetSelectionCut(selcut_zmumu_p)
zmup_jeteff.SetPassCut(selcut_zmumu_pass_p)
zmup_jeteff.AddTree(zmumuj.MUt)
zmup_jeteff.AddTree(zmumuj.MDt)
zmup_jeteff.AddVars(plusvariables)
zmup_jeteff.AddVars(plusjetvars)
zmup_jeteff.SetPltRange("muminus_mcjet_PHI" , 50 , -TMath.Pi() , TMath.Pi() )
zmup_jeteff.MakeEntryLists()
zmup_jeteff.MakeHists()
zmup_jeteff.MakeEfficiencyGraph()
zmup_jeteff.SaveToFile()

zmum_jeteff = EfficiencyClass("zmum_seleff")
zmum_jeteff.SetSelectionCut(selcut_zmumu_m)
zmum_jeteff.SetPassCut(selcut_zmumu_pass_m)
zmum_jeteff.AddTree(zmumuj.MUt)
zmum_jeteff.AddTree(zmumuj.MDt)
zmum_jeteff.AddVars(variables)
zmum_jeteff.AddVars(jetvars)
zmum_jeteff.SetPltRange("muminus_mcjet_PHI" , 50 , -TMath.Pi() , TMath.Pi() )
zmum_jeteff.MakeEntryLists()
zmum_jeteff.MakeHists()
zmum_jeteff.MakeEfficiencyGraph()
zmum_jeteff.SaveToFile()

zmup_mc2012 = EfficiencyClass("zmup_mc2012_seleff")
zmup_mc2012.SetSelectionCut(selcut_zmumu_p)
zmup_mc2012.SetPassCut(selcut_zmumu_pass_p)
zmup_mc2012.AddTree(zmumuj_mc2012.MUt)
zmup_mc2012.AddTree(zmumuj_mc2012.MDt)
zmup_mc2012.AddVars(plusvariables)
zmup_mc2012.AddVars(plusjetvars)
zmup_mc2012.SetPltRange("muminus_mcjet_PHI" , 50 , -TMath.Pi() , TMath.Pi() )
zmup_mc2012.MakeEntryLists()
zmup_mc2012.MakeHists()
zmup_mc2012.MakeEfficiencyGraph()
zmup_mc2012.SaveToFile()

zmum_mc2012 = EfficiencyClass("zmum_mc2012_seleff")
zmum_mc2012.SetSelectionCut(selcut_zmumu_m)
zmum_mc2012.SetPassCut(selcut_zmumu_pass_m)
zmum_mc2012.AddTree(zmumuj_mc2012.MUt)
zmum_mc2012.AddTree(zmumuj_mc2012.MDt)
zmum_mc2012.AddVars(variables)
zmum_mc2012.AddVars(jetvars)
zmum_mc2012.SetPltRange("muminus_mcjet_PHI" , 50 , -TMath.Pi() , TMath.Pi() )
zmum_mc2012.MakeEntryLists()
zmum_mc2012.MakeHists()
zmum_mc2012.MakeEfficiencyGraph()
zmum_mc2012.SaveToFile()

wmup_mc2012 = EfficiencyClass("wmup_mc2012_seleff")
wmup_mc2012.SetSelectionCut(selcut_recbase + plus)
wmup_mc2012.SetPassCut(selcut_base)
wmup_mc2012.AddTree(wmuj_mc2012.MUt)
wmup_mc2012.AddTree(wmuj_mc2012.MDt)
wmup_mc2012.AddVars(variables)
wmup_mc2012.AddVars(jetvars)
wmup_mc2012.SetPltRange("muminus_mcjet_PHI" , 50 , -TMath.Pi() , TMath.Pi() )
wmup_mc2012.MakeEntryLists()
wmup_mc2012.MakeHists()
wmup_mc2012.MakeEfficiencyGraph()
wmup_mc2012.SaveToFile()

wmum_mc2012 = EfficiencyClass("wmum_mc2012_seleff")
wmum_mc2012.SetSelectionCut(selcut_recbase + minus)
wmum_mc2012.SetPassCut(selcut_base)
wmum_mc2012.AddTree(wmuj_mc2012.MUt)
wmum_mc2012.AddTree(wmuj_mc2012.MDt)
wmum_mc2012.AddVars(variables)
wmum_mc2012.AddVars(jetvars)
wmum_mc2012.SetPltRange("muminus_mcjet_PHI" , 50 , -TMath.Pi() , TMath.Pi() )
wmum_mc2012.MakeEntryLists()
wmum_mc2012.MakeHists()
wmum_mc2012.MakeEfficiencyGraph()
wmum_mc2012.SaveToFile()

saveTGraph('wm_sel_eff_ptj.dat',  wmum_mc2012.GetVar("Jet_PT").GetEffGraph())
saveTGraph('wm_sel_eff_etaj.dat', wmum_mc2012.GetVar("Jet_ETA").GetEffGraph())
saveTGraph('wm_sel_eff_eta.dat' , wmum_mc2012.GetVar("ETA").GetEffGraph())
saveTGraphErrs('wm_sel_efferrs_ptj.dat',  wmum_mc2012.GetVar("Jet_PT").GetEffGraph())
saveTGraphErrs('wm_sel_efferrs_etaj.dat', wmum_mc2012.GetVar("Jet_ETA").GetEffGraph())
saveTGraphErrs('wm_sel_efferrs_eta.dat' , wmum_mc2012.GetVar("ETA").GetEffGraph())

saveTGraph('wp_sel_eff_ptj.dat',  wmup_mc2012.GetVar("Jet_PT").GetEffGraph())
saveTGraph('wp_sel_eff_etaj.dat', wmup_mc2012.GetVar("Jet_ETA").GetEffGraph())
saveTGraph('wp_sel_eff_eta.dat' , wmup_mc2012.GetVar("ETA").GetEffGraph())
saveTGraphErrs('wp_sel_efferrs_ptj.dat',  wmup_mc2012.GetVar("Jet_PT").GetEffGraph())
saveTGraphErrs('wp_sel_efferrs_etaj.dat', wmup_mc2012.GetVar("Jet_ETA").GetEffGraph())
saveTGraphErrs('wp_sel_efferrs_eta.dat' , wmup_mc2012.GetVar("ETA").GetEffGraph())
