from ROOT import *

wj_powheg   = TFile("/user2/sfarry/Generators/python/Wj_8TeV_powheg.root")
wj_mcatnlo  = TFile("/user2/sfarry/Generators/python/Wj_8TeV_amcatnlo.root")
zj_powheg   = TFile("/user2/sfarry/Generators/python/Zj_8TeV_powheg.root")
zj_mcatnlo  = TFile("/user2/sfarry/Generators/python/Zj_8TeV_amcatnlo.root")

wzj_powheg  = TFile("/user2/sfarry/Generators/python/WZj_8TeV_powheg.root")
wzj_mcatnlo = TFile("/user2/sfarry/Generators/python/WZj_8TeV_amcatnlo.root")
'''
print "cswp_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wj_powheg.Get('etaj_plus_tot').GetVal(),wj_powheg.Get('etaj_plus_scaleerr_hi').GetVal(),wj_powheg.Get('etaj_plus_scaleerr_lo').GetVal(), wj_powheg.Get('etaj_plus_pdferr').GetVal(), wj_powheg.Get('etaj_plus_pdferr').GetVal(), wj_powheg.Get('etaj_plus_toterr_hi'), wj_powheg.Get('etaj_plus_toterr_lo'))
print "cswm_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wj_powheg.Get('etaj_minus_tot').GetVal(),wj_powheg.Get('etaj_minus_scaleerr_hi').GetVal(),wj_powheg.Get('etaj_minus_scaleerr_lo').GetVal(), wj_powheg.Get('etaj_minus_pdferr').GetVal(), wj_powheg.Get('etaj_minus_pdferr').GetVal())
print "csz_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(zj_powheg.Get('etaj_tot').GetVal(),zj_powheg.Get('etaj_scaleerr_hi').GetVal(),zj_powheg.Get('etaj_scaleerr_lo').GetVal(), zj_powheg.Get('etaj_pdferr').GetVal(), zj_powheg.Get('etaj_pdferr').GetVal())

print "rwz_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_powheg.Get('etaj_rwz').GetVal(),wzj_powheg.Get('etaj_rwz_scale_errhi').GetVal(),wzj_powheg.Get('etaj_rwz_scale_errlo').GetVal(), wzj_powheg.Get('etaj_rwz_pdferr').GetVal(), wzj_powheg.Get('etaj_rwz_pdferr').GetVal())
print "rwpz_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_powheg.Get('etaj_rwpz').GetVal(),wzj_powheg.Get('etaj_rwpz_scale_errhi').GetVal(),wzj_powheg.Get('etaj_rwpz_scale_errlo').GetVal(), wzj_powheg.Get('etaj_rwpz_pdferr').GetVal(), wzj_powheg.Get('etaj_rwpz_pdferr').GetVal())
print "rwmz_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_powheg.Get('etaj_rwmz').GetVal(),wzj_powheg.Get('etaj_rwmz_scale_errhi').GetVal(),wzj_powheg.Get('etaj_rwmz_scale_errlo').GetVal(), wzj_powheg.Get('etaj_rwmz_pdferr').GetVal(), wzj_powheg.Get('etaj_rwmz_pdferr').GetVal())
print "rwpm_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_powheg.Get('etaj_rwpm').GetVal(),wzj_powheg.Get('etaj_rwpm_scale_errhi').GetVal(),wzj_powheg.Get('etaj_rwpm_scale_errlo').GetVal(), wzj_powheg.Get('etaj_rwpm_pdferr').GetVal(), wzj_powheg.Get('etaj_rwpm_pdferr').GetVal())

print "a_powheg = [ %2.4f, %2.4f, %2.4f, %2.4f, %2.4f, %2.4f, %2.4f]"%(wj_powheg.Get('asymm_eta_tot').GetVal(),wj_powheg.Get('asymm_eta_tot_scaleerr_hi').GetVal(),wj_powheg.Get('asymm_eta_tot_scaleerr_lo').GetVal(), wj_powheg.Get('asymm_eta_tot_pdferr').GetVal(), wj_powheg.Get('asymm_eta_tot_pdferr').GetVal())
'''

print "cswp_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wj_powheg.Get('etaj_plus_tot').GetVal(),wj_powheg.Get('etaj_plus_scaleerr_hi').GetVal(),wj_powheg.Get('etaj_plus_scaleerr_lo').GetVal(), wj_powheg.Get('etaj_plus_pdferr').GetVal(), wj_powheg.Get('etaj_plus_pdferr').GetVal(), wj_powheg.Get('etaj_plus_toterr_hi').GetVal(), wj_powheg.Get('etaj_plus_toterr_lo').GetVal())
print "cswm_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wj_powheg.Get('etaj_minus_tot').GetVal(),wj_powheg.Get('etaj_minus_scaleerr_hi').GetVal(),wj_powheg.Get('etaj_minus_scaleerr_lo').GetVal(), wj_powheg.Get('etaj_minus_pdferr').GetVal(), wj_powheg.Get('etaj_minus_pdferr').GetVal(), wj_powheg.Get('etaj_minus_toterr_hi').GetVal(), wj_powheg.Get('etaj_minus_toterr_lo').GetVal())
print "csz_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(zj_powheg.Get('etaj_tot').GetVal(),zj_powheg.Get('etaj_scaleerr_hi').GetVal(),zj_powheg.Get('etaj_scaleerr_lo').GetVal(), zj_powheg.Get('etaj_pdferr').GetVal(), zj_powheg.Get('etaj_pdferr').GetVal(), zj_powheg.Get('etaj_toterr_hi').GetVal(), zj_powheg.Get('etaj_toterr_lo').GetVal())

print "rwz_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_powheg.Get('etaj_rwz').GetVal(),wzj_powheg.Get('etaj_rwz_scale_errhi').GetVal(),wzj_powheg.Get('etaj_rwz_scale_errlo').GetVal(), wzj_powheg.Get('etaj_rwz_pdferr').GetVal(), wzj_powheg.Get('etaj_rwz_pdferr').GetVal(), wzj_powheg.Get('etaj_rwz_tot_errhi').GetVal(), wzj_powheg.Get('etaj_rwz_tot_errlo').GetVal())
print "rwpz_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_powheg.Get('etaj_rwpz').GetVal(),wzj_powheg.Get('etaj_rwpz_scale_errhi').GetVal(),wzj_powheg.Get('etaj_rwpz_scale_errlo').GetVal(), wzj_powheg.Get('etaj_rwpz_pdferr').GetVal(), wzj_powheg.Get('etaj_rwpz_pdferr').GetVal(), wzj_powheg.Get('etaj_rwpz_tot_errhi').GetVal(), wzj_powheg.Get('etaj_rwpz_tot_errlo').GetVal())
print "rwmz_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_powheg.Get('etaj_rwmz').GetVal(),wzj_powheg.Get('etaj_rwmz_scale_errhi').GetVal(),wzj_powheg.Get('etaj_rwmz_scale_errlo').GetVal(), wzj_powheg.Get('etaj_rwmz_pdferr').GetVal(), wzj_powheg.Get('etaj_rwmz_pdferr').GetVal(), wzj_powheg.Get('etaj_rwmz_tot_errhi').GetVal(), wzj_powheg.Get('etaj_rwmz_tot_errlo').GetVal())
print "rwpm_powheg = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_powheg.Get('etaj_rwpm').GetVal(),wzj_powheg.Get('etaj_rwpm_scale_errhi').GetVal(),wzj_powheg.Get('etaj_rwpm_scale_errlo').GetVal(), wzj_powheg.Get('etaj_rwpm_pdferr').GetVal(), wzj_powheg.Get('etaj_rwpm_pdferr').GetVal(), wzj_powheg.Get('etaj_rwpm_tot_errhi').GetVal(), wzj_powheg.Get('etaj_rwpm_tot_errlo').GetVal())

print "a_powheg = [ %2.4f, %2.4f, %2.4f, %2.4f, %2.4f, %2.4f, %2.4f]"%(wj_powheg.Get('asymm_eta_tot').GetVal(),wj_powheg.Get('asymm_eta_tot_scaleerr_hi').GetVal(),wj_powheg.Get('asymm_eta_tot_scaleerr_lo').GetVal(), wj_powheg.Get('asymm_eta_tot_pdferr').GetVal(), wj_powheg.Get('asymm_eta_tot_pdferr').GetVal(), wj_powheg.Get('asymm_eta_tot_errhi').GetVal(), wj_powheg.Get('asymm_eta_tot_errlo').GetVal())



print "cswp_mcatnlo = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wj_mcatnlo.Get('etaj_plus_tot').GetVal(),wj_mcatnlo.Get('etaj_plus_scaleerr_hi').GetVal(),wj_mcatnlo.Get('etaj_plus_scaleerr_lo').GetVal(), wj_mcatnlo.Get('etaj_plus_pdferr').GetVal(), wj_mcatnlo.Get('etaj_plus_pdferr').GetVal(), wj_mcatnlo.Get('etaj_plus_toterr_hi').GetVal(), wj_mcatnlo.Get('etaj_plus_toterr_lo').GetVal())
print "cswm_mcatnlo = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wj_mcatnlo.Get('etaj_minus_tot').GetVal(),wj_mcatnlo.Get('etaj_minus_scaleerr_hi').GetVal(),wj_mcatnlo.Get('etaj_minus_scaleerr_lo').GetVal(), wj_mcatnlo.Get('etaj_minus_pdferr').GetVal(), wj_mcatnlo.Get('etaj_minus_pdferr').GetVal(), wj_mcatnlo.Get('etaj_minus_toterr_hi').GetVal(), wj_mcatnlo.Get('etaj_minus_toterr_lo').GetVal())
print "csz_mcatnlo = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(zj_mcatnlo.Get('etaj_tot').GetVal(),zj_mcatnlo.Get('etaj_scaleerr_hi').GetVal(),zj_mcatnlo.Get('etaj_scaleerr_lo').GetVal(), zj_mcatnlo.Get('etaj_pdferr').GetVal(), zj_mcatnlo.Get('etaj_pdferr').GetVal(), zj_mcatnlo.Get('etaj_toterr_hi').GetVal(), zj_mcatnlo.Get('etaj_toterr_lo').GetVal())

print "rwz_mcatnlo = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_mcatnlo.Get('etaj_rwz').GetVal(),wzj_mcatnlo.Get('etaj_rwz_scale_errhi').GetVal(),wzj_mcatnlo.Get('etaj_rwz_scale_errlo').GetVal(), wzj_mcatnlo.Get('etaj_rwz_pdferr').GetVal(), wzj_mcatnlo.Get('etaj_rwz_pdferr').GetVal(), wzj_mcatnlo.Get('etaj_rwz_tot_errhi').GetVal(), wzj_mcatnlo.Get('etaj_rwz_tot_errlo').GetVal())
print "rwpz_mcatnlo = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_mcatnlo.Get('etaj_rwpz').GetVal(),wzj_mcatnlo.Get('etaj_rwpz_scale_errhi').GetVal(),wzj_mcatnlo.Get('etaj_rwpz_scale_errlo').GetVal(), wzj_mcatnlo.Get('etaj_rwpz_pdferr').GetVal(), wzj_mcatnlo.Get('etaj_rwpz_pdferr').GetVal(), wzj_mcatnlo.Get('etaj_rwpz_tot_errhi').GetVal(), wzj_mcatnlo.Get('etaj_rwpz_tot_errlo').GetVal())
print "rwmz_mcatnlo = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_mcatnlo.Get('etaj_rwmz').GetVal(),wzj_mcatnlo.Get('etaj_rwmz_scale_errhi').GetVal(),wzj_mcatnlo.Get('etaj_rwmz_scale_errlo').GetVal(), wzj_mcatnlo.Get('etaj_rwmz_pdferr').GetVal(), wzj_mcatnlo.Get('etaj_rwmz_pdferr').GetVal(), wzj_mcatnlo.Get('etaj_rwmz_tot_errhi').GetVal(), wzj_mcatnlo.Get('etaj_rwmz_tot_errlo').GetVal())
print "rwpm_mcatnlo = [ %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f, %2.3f]"%(wzj_mcatnlo.Get('etaj_rwpm').GetVal(),wzj_mcatnlo.Get('etaj_rwpm_scale_errhi').GetVal(),wzj_mcatnlo.Get('etaj_rwpm_scale_errlo').GetVal(), wzj_mcatnlo.Get('etaj_rwpm_pdferr').GetVal(), wzj_mcatnlo.Get('etaj_rwpm_pdferr').GetVal(), wzj_mcatnlo.Get('etaj_rwpm_tot_errhi').GetVal(), wzj_mcatnlo.Get('etaj_rwpm_tot_errlo').GetVal())

print "a_mcatnlo = [ %2.4f, %2.4f, %2.4f, %2.4f, %2.4f, %2.4f, %2.4f]"%(wj_mcatnlo.Get('asymm_eta_tot').GetVal(),wj_mcatnlo.Get('asymm_eta_tot_scaleerr_hi').GetVal(),wj_mcatnlo.Get('asymm_eta_tot_scaleerr_lo').GetVal(), wj_mcatnlo.Get('asymm_eta_tot_pdferr').GetVal(), wj_mcatnlo.Get('asymm_eta_tot_pdferr').GetVal(), wj_mcatnlo.Get('asymm_eta_tot_errhi').GetVal(), wj_mcatnlo.Get('asymm_eta_tot_errlo').GetVal())
