from PlotTools import *
from ROOT import TFile, TTree, TH1F, TLine, TMath

from Style import *
SetLHCbStyle()

z0mass_eta = TLine(2.0, 91.1876, 4.5, 91.1876)
z0mass_eta.SetLineColor(44)
z0mass_eta.SetLineStyle(7)
z0mass_phi = TLine(-TMath.Pi(), 91.1876, TMath.Pi(), 91.1876)
z0mass_phi.SetLineColor(44)
z0mass_phi.SetLineStyle(7)

zeromass_eta = TLine(2.0, 0.0, 4.5, 0.0)
zeromass_eta.SetLineColor(44)
zeromass_eta.SetLineStyle(7)
zeromass_phi = TLine(-TMath.Pi(), 0.0, TMath.Pi(), 0.0)
zeromass_phi.SetLineColor(44)
zeromass_phi.SetLineStyle(7)

f = TFile("/user2/sfarry/momentumscale/output/z0_test/output.root")
g = TFile("/user2/sfarry/momentumscale/output/ZMuMu_MC2015/output.root")

p = Plot([f.Get('mass_v_muplus_ETA_magup'), f.Get('mass_v_muplus_ETA_magdown')])
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_eta_plus_2015')
p.setProp('location', '/user2/sfarry/momentumscale/figures')
p.setProp('ylims', [88, 94])
p.setProp('colors', ['red', 'blue'])
p.setProp('markerstyles', 20)
p.setProp('labels', ['2015 Data - MagUp', '2015 Data - MagDown'])
p.setProp('xlabel', '#eta (#mu^{+})')
p.setProp('leglims', [0.2, 0.7, 0.55, 0.9])
p.setProp('extraObjs', [z0mass_eta])
p.drawROOT()
p.plots = [f.Get('mass_v_muminus_ETA_magup'), f.Get('mass_v_muminus_ETA_magdown')]
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_eta_minus_2015')
p.setProp('xlabel', '#eta (#mu^{-})')
p.drawROOT()

p = Plot([f.Get('mass_v_muplus_PHI_magup'), f.Get('mass_v_muplus_PHI_magdown')])
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_phi_plus_2015')
p.setProp('location', '/user2/sfarry/momentumscale/figures')
p.setProp('ylims', [88, 94])
p.setProp('colors', ['red', 'blue'])
p.setProp('markerstyles', 20)
p.setProp('labels', ['2015 Data - MagUp', '2015 Data - MagDown'])
p.setProp('xlabel', '#phi (#mu^{+})')
p.setProp('leglims', [0.2, 0.7, 0.55, 0.9])
p.setProp('extraObjs', [z0mass_phi])
p.drawROOT()
p.plots = [f.Get('mass_v_muminus_PHI_magup'), f.Get('mass_v_muminus_PHI_magdown')]
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_phi_minus_2015')
p.setProp('xlabel', '#eta (#phi^{-})')
p.drawROOT()

p = Plot([f.Get('mass_v_muplus_Refit_ETA_magup'), f.Get('mass_v_muplus_Refit_ETA_magdown')])
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_eta_plus_refit_2015')
p.setProp('location', '/user2/sfarry/momentumscale/figures')
p.setProp('ylims', [88, 94])
p.setProp('colors', ['red', 'blue'])
p.setProp('markerstyles', 20)
p.setProp('labels', ['2015 Data (Refit) - MagUp', '2015 Data (Refit) - MagDown'])
p.setProp('xlabel', '#eta (#mu^{+})')
p.setProp('leglims', [0.2, 0.7, 0.6, 0.9])
p.setProp('extraObjs', [z0mass_eta])
p.drawROOT()
p.plots = [f.Get('mass_v_muminus_Refit_ETA_magup'), f.Get('mass_v_muminus_Refit_ETA_magdown')]
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_eta_minus_refit_2015')
p.setProp('xlabel', '#eta (#mu^{-})')
p.drawROOT()

p = Plot([f.Get('mass_v_muplus_Refit_PHI_magup'), f.Get('mass_v_muplus_Refit_PHI_magdown')])
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_phi_plus_refit_2015')
p.setProp('location', '/user2/sfarry/momentumscale/figures')
p.setProp('ylims', [88, 94])
p.setProp('colors', ['red', 'blue'])
p.setProp('markerstyles', 20)
p.setProp('labels', ['2015 Data (Refit) - MagUp', '2015 Data (Refit) - MagDown'])
p.setProp('xlabel', '#phi (#mu^{+})')
p.setProp('leglims', [0.2, 0.7, 0.6, 0.9])
p.setProp('extraObjs', [z0mass_phi])
p.drawROOT()
p.plots = [f.Get('mass_v_muminus_Refit_PHI_magup'), f.Get('mass_v_muminus_Refit_PHI_magdown')]
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_phi_minus_refit_2015')
p.setProp('xlabel', '#phi (#mu^{-})')
p.drawROOT()


p = Plot([g.Get('mass_v_muplus_ETA_magup'), g.Get('mass_v_muplus_ETA_magdown')])
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_eta_plus_mc2015')
p.setProp('location', '/user2/sfarry/momentumscale/figures')
p.setProp('ylims', [88, 94])
p.setProp('colors', ['red', 'blue'])
p.setProp('markerstyles', 20)
p.setProp('labels', ['MC 2015 - MagUp', 'MC 2015 - MagDown'])
p.setProp('xlabel', '#eta (#mu^{+})')
p.setProp('leglims', [0.2, 0.7, 0.55, 0.9])
p.setProp('extraObjs', [z0mass_eta])
p.drawROOT()
p.plots = [g.Get('mass_v_muminus_ETA_magup'), g.Get('mass_v_muminus_ETA_magdown')]
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_eta_minus_mc2015')
p.setProp('xlabel', '#eta (#mu^{-})')
p.drawROOT()

p = Plot([g.Get('mass_v_muplus_PHI_magup'), g.Get('mass_v_muplus_PHI_magdown')])
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_phi_plus_mc2015')
p.setProp('location', '/user2/sfarry/momentumscale/figures')
p.setProp('ylims', [88, 94])
p.setProp('colors', ['red', 'blue'])
p.setProp('markerstyles', 20)
p.setProp('labels', ['MC 2015 - MagUp', 'MC 2015 - MagDown'])
p.setProp('xlabel', '#phi (#mu^{+})')
p.setProp('leglims', [0.2, 0.7, 0.55, 0.9])
p.setProp('extraObjs', [z0mass_phi])
p.drawROOT()
p.plots = [g.Get('mass_v_muminus_PHI_magup'), g.Get('mass_v_muminus_PHI_magdown')]
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_mass_v_phi_minus_mc2015')
p.setProp('xlabel', '#phi (#mu^{-})')
p.drawROOT()



p = Plot([f.Get('sigma_v_muplus_ETA_magup'), f.Get('sigma_v_muplus_ETA_magdown'),f.Get('sigma_v_muplus_Refit_ETA_magup'), f.Get('sigma_v_muplus_Refit_ETA_magdown')])
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_sigma_v_eta_plus_2015')
p.setProp('location', '/user2/sfarry/momentumscale/figures')
p.setProp('ylims', [0.001,5])
p.setProp('colors', ['red', 'blue', 8, ROOT.kYellow-3])
p.setProp('markerstyles', 20)
p.setProp('labels', ['2015 Data - MagUp', '2015 Data - MagDown', '2015 Data - MagUp (Refit)', '2015 Data - MagDown (Refit)'])
p.setProp('xlabel', '#eta (#mu^{+})')
p.setProp('leglims', [0.2, 0.7, 0.65, 0.9])
p.setProp('toCompare', { 1 : {1, 3}, 0 : {0, 2} })
p.setProp('ycomplims', [-1.9, 1.9])
p.setProp('compareAsRatio', False)
p.setProp('compObjs', [zeromass_eta])
p.setProp('ylabel', 'Mass Resolution (GeV)')
p.setProp('canvas_size', [800, 800])
p.drawROOT()
p.plots = [f.Get('sigma_v_muminus_ETA_magup'), f.Get('sigma_v_muminus_ETA_magdown'), f.Get('sigma_v_muminus_Refit_ETA_magup'), f.Get('sigma_v_muminus_Refit_ETA_magdown')]
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_sigma_v_eta_minus_2015')
p.setProp('xlabel', '#eta (#mu^{-})')
p.drawROOT()

p = Plot([f.Get('sigma_v_muplus_PHI_magup'), f.Get('sigma_v_muplus_PHI_magdown'), f.Get('sigma_v_muplus_Refit_PHI_magup'), f.Get('sigma_v_muplus_Refit_PHI_magdown')])
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_sigma_v_phi_plus_2015')
p.setProp('location', '/user2/sfarry/momentumscale/figures')
p.setProp('ylims', [0.001,5])
p.setProp('colors', ['red', 'blue', 8, ROOT.kYellow-3])
p.setProp('markerstyles', 20)
p.setProp('labels', ['2015 Data - MagUp', '2015 Data - MagDown', '2015 Data - MagUp (Refit)', '2015 Data - MagUp (Refit)'])
p.setProp('xlabel', '#phi (#mu^{+})')
p.setProp('leglims', [0.2, 0.7, 0.65, 0.9])
p.setProp('compObjs', [zeromass_phi])
p.setProp('toCompare', { 1 : {1, 3}, 0 : {0, 2} })
p.setProp('ycomplims', [-1.9, 1.9])
p.setProp('compareAsRatio', False)
p.setProp('canvas_size', [800, 800])
p.setProp('ylabel', 'Mass Resolution (GeV)')
p.drawROOT()
p.plots = [f.Get('sigma_v_muminus_PHI_magup'), f.Get('sigma_v_muminus_PHI_magdown'),f.Get('sigma_v_muminus_Refit_PHI_magup'), f.Get('sigma_v_muminus_Refit_PHI_magdown')]
for plot in p.plots: plot.Scale(0.001)
p.setProp('filename', 'z0_sigma_v_phi_minus_2015')
p.setProp('xlabel', '#phi (#mu^{-})')
p.drawROOT()

