from ROOT import *
from PlotTools import *
from Style import *
SetLHCbStyle()

f = TFile("/user2/sfarry/workspaces/strange/tmvaDVout.root")

p = Plot([f.Get('Method_BDT/BDTB/MVA_BDTB_rejBvsS'), f.Get('Method_BDT/BDT/MVA_BDT_rejBvsS'), f.Get('Method_BDT/BDTAdaBoost/MVA_BDTAdaBoost_rejBvsS')])
p.setProp('filename', 'mva_comp')
p.setProp('location', '/user2/sfarry/workspaces/strange/figures')
p.setProp('drawOpts', 'l1')
p.setProp('linecolors', ['red', 'blue', 'green'])
p.setProp('fillstyles', 0)
p.setProp('labels', ['Bagging', 'Grad', 'Adaptive'])
p.setProp('markerstyles', 20)
p.setProp('xlabel', 'Signal Efficiency')
p.setProp('ylabel', 'Background Rejection')
p.setProp('leglims', [0.2, 0.2, 0.7, 0.4])
p.drawROOT()

ptbins = [0, 10, 20, 30, 50, 100]

from Jawa import *
sig = Template('sig')
sig.SetSelCut(TCut('classID == 0'))
sig.AddTree(f.Get('TrainTree'))
sig.AddVar(['BDT', 'BDT', 50, -1, 1])
sig.AddVar(['ptj', 'jet_PT/1000.0', ptbins])
sig.Add2DVar(['BDT', 'ptj'])
sig.Run()
sig.SaveToFile()

bkg = Template('bkg')
bkg.SetSelCut(TCut('classID == 1'))
bkg.AddTree(f.Get('TrainTree'))
bkg.AddVar(['BDT', 'BDT', 50, -1, 1])
bkg.AddVar(['ptj', 'jet_PT/1000.0', ptbins])
bkg.Add2DVar(['BDT', 'ptj'])
bkg.Run()
bkg.SaveToFile()



sig_h = sig.Get2DVar('BDT', 'ptj').GetHist()
bkg_h = bkg.Get2DVar('BDT', 'ptj').GetHist()
for i in range(len(ptbins) - 1):
    tt = TPaveText(0.2, 0.4, 0.45, 0.6, "NDC")
    tt.AddText(str(ptbins[i])+" < p_{T}^{j} < "+str(ptbins[i+1])+" GeV")
    tt.SetFillStyle(0)
    tt.SetBorderSize(0)
    p = Plot([sig_h.ProjectionX(sig_h.GetName()+str(i), i+1, i+1), bkg_h.ProjectionX(sig_h.GetName()+str(i), i+1, i+1)])
    p.setProp('filename', 'comp'+str(i))
    p.setProp('location', '/user2/sfarry/workspaces/strange/figures')
    p.setProp('drawOpts', 'h1')
    p.setProp('linecolors', ['red', 'blue'])
    p.setProp('fillstyles', 0)
    p.setProp('labels', ['Strange Jets', 'Light Jets'])
    p.setProp('markerstyles', 20)
    p.setProp('xlabel', 'BDT')
    p.setProp('ylabel', '[A.U.]')
    p.setProp('leglims', [0.2, 0.7, 0.5, 0.9])
    p.setProp('normalised', True)
    p.setProp('ynormlims', [0, 0.2])
    p.setProp('extraObjs', [tt])
    p.drawROOT()


p2 = Plot([sig_h.ProjectionX(sig_h.GetName()+str(i)+"2", i+1, i+1) for i in range(len(ptbins)-1)])
tt2 = TPaveText(0.2, 0.2, 0.45, 0.35, "NDC")
tt2.AddText('Strange Jets')
tt2.SetFillStyle(0)
tt2.SetBorderSize(0)
p2.setProp('filename', 'sigcomp')
p2.setProp('location', '/user2/sfarry/workspaces/strange/figures')
p2.setProp('drawOpts', 'h')
p2.setProp('linecolors', ['red', 'blue', 'green', 'black', 'yellow'])
p2.setProp('fillstyles', 0)
p2.setProp('labels', [str(ptbins[i])+" < p_{T}^{j} < "+str(ptbins[i+1])+" GeV" for i in range(len(ptbins)-1)])
p2.setProp('markerstyles', 20)
p2.setProp('xlabel', 'BDT')
p2.setProp('ylabel', '[A.U.]')
p2.setProp('leglims', [0.15, 0.5, 0.45, 0.9])
p2.setProp('normalised', True)
p2.setProp('ynormlims', [0, 0.2])
p2.setProp('extraObjs', [tt2])
p2.drawROOT()


p2 = Plot([bkg_h.ProjectionX(bkg_h.GetName()+str(i)+"2", i+1, i+1) for i in range(len(ptbins)-1)])
tt3 = TPaveText(0.2, 0.2, 0.45, 0.35, "NDC")
tt3.AddText('Light Jets')
tt3.SetFillStyle(0)
tt3.SetBorderSize(0)
p2.setProp('filename', 'bkgcomp')
p2.setProp('location', '/user2/sfarry/workspaces/strange/figures')
p2.setProp('drawOpts', 'h')
p2.setProp('linecolors', ['red', 'blue', 'green', 'black', 'yellow'])
p2.setProp('fillstyles', 0)
p2.setProp('labels', [str(ptbins[i])+" < p_{T}^{j} < "+str(ptbins[i+1])+" GeV" for i in range(len(ptbins)-1)])
p2.setProp('markerstyles', 20)
p2.setProp('xlabel', 'BDT')
p2.setProp('ylabel', '[A.U.]')
p2.setProp('leglims', [0.15, 0.5, 0.45, 0.9])
p2.setProp('normalised', True)
p2.setProp('ynormlims', [0, 0.2])
p2.setProp('extraObjs', [tt3])
p2.drawROOT()
